[tool.poetry]
name = "django-djazztro"
version = "0.2.0"
description = "Python-side of the Djazztro stack, provides a template backend for using Astro files."
authors = ["Ben C <bwc9876@gmail.com>"]
readme = "../../README.md"
packages = [{include = "django_djazztro"}]

[tool.poetry.dependencies]
python = "^3.6"
django = "^4.1.3"
requests = "^2.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
